level:
  ROOT: ERROR
  org.springframework.web: ERROR
  liquibase: INFO

spring:
  profiles:
    active: "prod"

okta:
  oauth2:
    issuer: https://dev-958433.okta.com/oauth2/default
    client-id: 0oa4u7s7jowBgKy6W4x6
    client-secret: udX0cFsj3UsCznuiFbmE1M04U3_aEVIgSPdmgCL1
