level:
  ROOT: ERROR
  org.springframework.web: ERROR
  liquibase: INFO

spring:
  profiles:
    active: "prod"

okta:
  oauth2:
    issuer: https://dev-958433.okta.com/oauth2/default
    client-id: 0oazig0adjD1PgAjO356
    client-secret: iNxF-y6iJACN2eeY8MO-bJ7IdhcSEjt1YXrrNfc0

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false