level:
  ROOT: ERROR
  org.springframework.web: ERROR
  liquibase: INFO

server:
  port: 8761

ribbon:
  eureka:
    enabled: true

management:
  security:
    roles: SYSADMIN
  context-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

eureka:
  instance:
    appname: registry-server
    instanceId: registry-server:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    metadata-map:
      profile: ${spring.profiles.active}
      version: ${info.project.version}
  client:
    enabled: true
    #This is a eureka server no need to fetch registry
    fetch-registry: false
    #This is a eureka server so no need to register
    register-with-eureka: false
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    enable-self-preservation: false
    #timeout
    wait-time-in-ms-when-sync-empty: 0
  dashboard:
    path: /registry

#Name of the application
spring:
  application:
    name: registry-server