level:
  ROOT: ERROR
  org.springframework.web: ERROR
  liquibase: INFO

spring:
  profiles:
    active: "prod"
  security:
    user:
      roles: USER,ADMIN,SYSADMIN
      name: admin
      password: admin

#okta:
#  oauth2:
#    issuer: https://dev-958433.okta.com/oauth2/default
#    client-id: 0oa4u7s7jowBgKy6W4x6
#    client-secret: udX0cFsj3UsCznuiFbmE1M04U3_aEVIgSPdmgCL1

security:
  oauth2:
    client:
      accessTokenUri: https://dev-958433.okta.com/oauth2/default/v1/token
      userAuthorizationUri: https://dev-958433.okta.com/oauth2/default/v1/authorize
      clientId: 0oa4u7s7jowBgKy6W4x6
      clientSecret: udX0cFsj3UsCznuiFbmE1M04U3_aEVIgSPdmgCL1
      scope: openid profile email groups
    resource:
      userInfoUri: https://dev-958433.okta.com/oauth2/default/v1/userinfo

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://admin:${spring.security.user.password}@localhost:${server.port}/eureka/
